spring:
  profiles:
    active: "docker"
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
  application:
    name: equipes-ms
  datasource:
    url: 'jdbc:h2:mem:eqdb'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://eurekaserver:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: false
    #hostname: genres-ms
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

build:
  version: "1.0"
author:
  name: "salma Equipe"
  email: "salma_Equipe@gmail.com"