spring:
  profiles:
    active: "jour"
  config:
    import: "optional:configserver:http://localhost:9999/"
  application:
    name: equipes
  datasource:
    #url: "jdbc:h2:mem:eqdb"
    url: "jdbc:mysql://mysqldb:3308/test?useSSL=false&serverTimezone=UTC"
    username: root
    password:   root
  #h2:
    #console:
      #enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  eureka:
    client:
      service-url:
        defaultZone: "http://localhost:8761/eureka/"

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    prefer-ip-address: true
build:
  version: 1.0
author:
  name: "salma Equipe"
  email: "salma_Equipe@gmail.com"

